/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './**/*.{ts,tsx}',
    '!./node_modules/**',
    '!./functions/**',
    '!./docs/**',
  ],
  future: {
    hoverOnlyWhenSupported: true,
  },
  theme: {
    extend: {
      fontFamily: {
        sans: ['Karla', 'Helvetica', 'Arial', 'sans-serif'],
        display: ['"Instrument Serif"', 'Georgia', 'serif'],
        cursive: ['"Instrument Serif"', 'Georgia', 'serif'],
      },
      colors: {
        // Cool mist — light gray atmosphere, brand azure, soft land green
        primary: '#00C2FF',
        'primary-hover': '#00A8E0',
        secondary: '#3D9B6E',
        accent: '#00C2FF',
        'accent-soft': '#D6F0FA',
        warning: '#E0A04A',
        error: '#E56060',
        sky: '#00C2FF',
        'sky-light': '#5DD4FF',
        land: '#3D9B6E',
        'land-soft': '#D8EDE3',
        surface: '#E9EEF3',
        'surface-dark': '#DDE4EC',
        elevated: '#F5F8FB',
        'elevated-2': '#FFFFFF',
        text: '#15202B',
        'text-dark': '#15202B',
        muted: '#5A6A78',
        border: '#CCD6E0',
        glass: 'rgba(245, 248, 251, 0.88)',
        'glass-dark': 'rgba(233, 238, 243, 0.95)',
      },
      boxShadow: {
        'premium': '0 1px 0 rgba(255,255,255,0.7), 0 12px 32px rgba(21,32,43,0.08)',
        'premium-hover': '0 1px 0 rgba(255,255,255,0.8), 0 18px 40px rgba(21,32,43,0.12)',
        'glass': '0 8px 24px rgba(21,32,43,0.08)',
        'glass-bubble': '0 8px 24px rgba(21,32,43,0.08)',
        'inner-gloss': 'inset 0 1px 0 rgba(255,255,255,0.7)',
        'glow-primary': 'none',
        'glow-sky': 'none',
        'glow-accent': 'none',
        'glow-white': 'none',
        'logo-glow': 'none',
      },
      backgroundImage: {
        'glossy-gradient': 'linear-gradient(180deg, #F5F8FB 0%, #E9EEF3 100%)',
        'frutiger-gradient': 'linear-gradient(135deg, #E9EEF3 0%, #DDE8F2 50%, #D8EDE3 100%)',
        'frutiger-glass': 'linear-gradient(135deg, rgba(245,248,251,0.95) 0%, rgba(233,238,243,0.9) 100%)',
        'aurora': 'radial-gradient(ellipse at 70% 20%, rgba(0,194,255,0.22) 0%, transparent 50%), radial-gradient(ellipse at 15% 80%, rgba(61,155,110,0.16) 0%, transparent 48%)',
        'glass-gradient': 'linear-gradient(135deg, #F5F8FB 0%, #E9EEF3 100%)',
        'gel-blue': 'linear-gradient(180deg, #5DD4FF 0%, #00C2FF 48%, #00A8E0 100%)',
        'gel-gold': 'linear-gradient(180deg, #E0A04A 0%, #C4842E 100%)',
        'sky-gradient': 'linear-gradient(180deg, #D6F0FA 0%, #E9EEF3 100%)',
        'hero-atlas': 'linear-gradient(155deg, #DCEAF3 0%, #E9EEF3 40%, #E4EFE8 78%, #E9EEF3 100%)',
      },
      borderRadius: {
        'atlas': '0.75rem',
        'atlas-lg': '1rem',
      },
      animation: {
        'color-pulse': 'color-pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'wipe-screen': 'wipe-screen 1s cubic-bezier(0.77, 0, 0.175, 1) forwards',
        'float': 'float 6s ease-in-out infinite',
        'float-delayed': 'float 6s ease-in-out 3s infinite',
        'shimmer': 'shimmer 2s linear infinite',
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'spin-slow': 'spin 20s linear infinite',
        'breathe': 'breathe 6s ease-in-out infinite',
        'bounce-slow': 'bounce 3s infinite',
        'aero-wipe-in': 'aero-wipe-in 1s cubic-bezier(0.77, 0, 0.175, 1) forwards',
        'aero-wipe-out': 'aero-wipe-out 1s cubic-bezier(0.77, 0, 0.175, 1) forwards',
        'aero-wipe-full-forward': 'aero-wipe-full-forward 1.4s cubic-bezier(0.77, 0, 0.175, 1) forwards',
        'aero-wipe-full-backward': 'aero-wipe-full-backward 1.4s cubic-bezier(0.77, 0, 0.175, 1) forwards',
        'shake': 'shake 0.4s cubic-bezier(.36,.07,.19,.97) both',
        'timer-panic': 'timer-panic 0.5s ease-in-out infinite',
        'glow-pulse': 'glow-pulse 5s ease-in-out infinite',
        'glow-pulse-slow': 'glow-pulse-slow 4s ease-in-out infinite',
        'float-gentle': 'float-gentle 18s ease-in-out infinite',
        'float-gentle-delayed': 'float-gentle 22s ease-in-out 1.5s infinite',
        'fade-up': 'fade-up 0.6s ease-out both',
      },
      keyframes: {
        'breathe': {
          '0%, 100%': { transform: 'scale(1)', opacity: '1' },
          '50%': { transform: 'scale(1.03)', opacity: '0.9' },
        },
        'timer-panic': {
          '0%, 100%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.05)' },
        },
        'glow-pulse': {
          '0%, 100%': { opacity: '0.5' },
          '50%': { opacity: '0.8' },
        },
        'glow-pulse-slow': {
          '0%, 100%': { opacity: '0.6' },
          '50%': { opacity: '1' },
        },
        'float-gentle': {
          '0%, 100%': { transform: 'translate(0, 0)' },
          '50%': { transform: 'translate(0, -6px)' },
        },
        'aero-wipe-full-forward': {
          '0%': { transform: 'translateX(100%)', opacity: '1' },
          '35%, 65%': { transform: 'translateX(0)', opacity: '1' },
          '100%': { transform: 'translateX(-100%)', opacity: '1' },
        },
        'aero-wipe-full-backward': {
          '0%': { transform: 'translateX(-100%)', opacity: '1' },
          '35%, 65%': { transform: 'translateX(0)', opacity: '1' },
          '100%': { transform: 'translateX(100%)', opacity: '1' },
        },
        'shake': {
          '0%, 100%': { transform: 'translate3d(0, 0, 0)' },
          '10%, 30%, 50%, 70%, 90%': { transform: 'translate3d(-10px, 0, 0)' },
          '20%, 40%, 60%, 80%': { transform: 'translate3d(10px, 0, 0)' },
        },
        'aero-wipe-in': {
          '0%': { transform: 'translateX(100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        'aero-wipe-out': {
          '0%': { transform: 'translateX(0)', opacity: '1' },
          '100%': { transform: 'translateX(-100%)', opacity: '0' },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-12px)' },
        },
        'shimmer': {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'color-pulse': {
          '0%, 100%': { color: '#00C2FF' },
          '50%': { color: '#3D9B6E' },
        },
        'wipe-screen': {
          '0%': { transform: 'translateX(100%)', opacity: '0' },
          '35%': { transform: 'translateX(0)', opacity: '1' },
          '65%': { transform: 'translateX(0)', opacity: '1' },
          '100%': { transform: 'translateX(-100%)', opacity: '0' },
        },
        'fade-up': {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
};
